<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="1"
            tests="1">

  <testsuite name="01_test"
    errors="1" failures="1" hostname="" id="" package="01_test" skipped="0"
    tests="1" time="30.76" timestamp="">
  
    <testcase name="Test Google Search" classname="01_test" time="30.76" assertions="4">

    

    

      <failure message="Timed out while waiting for element &lt;input[id=&#34;call_number&#34;]&gt; to be visible for 5000 milliseconds. - expected &#34;visible&#34; but got: &#34;not visible&#34; (5292ms)">    at Object.Test Google Search (C:\Users\AndresCid\Documents\TELNORM\nightwatch\tests\01_test.js:25:10)</failure>

    
    <error message="Timed out while waiting for element &lt;input[id=&#34;call_number&#34;]&gt; to be visible for 5000 milliseconds. - expected [0;32m&#34;visible&#34;[0m but got: [0;31m&#34;not visible&#34;[0m [0;90m(5292ms)[0m" type="error"><![CDATA[
    Error
    at Object.Test Google Search (C:\Users\AndresCid\Documents\TELNORM\nightwatch\tests\01_test.js:25:10)
    at Context.call (C:\Users\AndresCid\Documents\TELNORM\nightwatch\node_modules\nightwatch\lib\testsuite\context.js:478:35)
    at TestCase.run (C:\Users\AndresCid\Documents\TELNORM\nightwatch\node_modules\nightwatch\lib\testsuite\testcase.js:58:31)
    at Runnable.__runFn (C:\Users\AndresCid\Documents\TELNORM\nightwatch\node_modules\nightwatch\lib\testsuite\index.js:759:80)
    at Runnable.run (C:\Users\AndresCid\Documents\TELNORM\nightwatch\node_modules\nightwatch\lib\testsuite\runnable.js:126:21)
    at TestSuite.executeRunnable (C:\Users\AndresCid\Documents\TELNORM\nightwatch\node_modules\nightwatch\lib\testsuite\index.js:912:49)
    at TestSuite.handleRunnable (C:\Users\AndresCid\Documents\TELNORM\nightwatch\node_modules\nightwatch\lib\testsuite\index.js:927:33)
    at C:\Users\AndresCid\Documents\TELNORM\nightwatch\node_modules\nightwatch\lib\testsuite\index.js:759:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DefaultRunner.runTestSuite (C:\Users\AndresCid\Documents\TELNORM\nightwatch\node_modules\nightwatch\lib\runner\test-runners\default.js:78:7)
    ]]></error>
    
    </testcase>
  

  
    <system-err>
       TimeoutError
   An error occurred while running .click() command on &lt;a[id=&#34;dial_manual_call&#34;]&gt;: element click intercepted: Element &lt;a href=&#34;javascript:void(0)&#34; class=&#34;btn btn-info webphone-phone-icon&#34; onclick=&#34;switchasmanual();&#34; id=&#34;dial_manual_call&#34; style=&#34;margin-right:1px;&#34;&gt;...&lt;/a&gt; is not clickable at point (73, 94). Other element would receive the click: &lt;div class=&#34;topbar-tools agent-dropdown-menu&#34; style=&#34;margin-left:-15px;&#34;&gt;...&lt;/div&gt;
  (Session info: chrome=112.0.5615.138)
    {&#34;error&#34;:{&#34;name&#34;:&#34;ElementClickInterceptedError&#34;,&#34;remoteStacktrace&#34;:&#34;&#34;},&#34;status&#34;:-1,&#34;value&#34;:null}

    Error location:
    C:\Users\AndresCid\Documents\TELNORM\nightwatch\tests\01_test.js:
    ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
     22 |         .click(&#39;button[type=&#34;submit&#34;]&#39;)
     23 |         .waitForElementVisible(&#39;a[id=&#34;dial_manual_call&#34;]&#39;)
     24 |         .click(&#39;a[id=&#34;dial_manual_call&#34;]&#39;) 
     25 |         .waitForElementVisible(&#39;input[id=&#34;call_number&#34;]&#39;)
     26 |         .setValue(&#39;input[id=&#34;call_number&#34;]&#39;, &#39;525532778745&#39;)
    ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

    </system-err>
  

    

  
  </testsuite>
</testsuites>
